In [1]:
import pandas as pd

In [9]:
df_exams = pd.read_csv("StudentsPerformance.csv")
df_exams.()

gender race/ethnicity parental level of education         lunch  \
0  female        group B           bachelor's degree      standard   
1  female        group C                some college      standard   
2  female        group B             master's degree      standard   
3    male        group A          associate's degree  free/reduced   
4    male        group C                some college      standard   
5  female        group B          associate's degree      standard   

  test preparation course  math score  reading score  writing score  
0                    none          72             72             74  
1               completed          69             90             88  
2                    none          90             95             93  
3                    none          47             57             44  
4                    none          76             78             75  
5                    none          71             83             78

In [15]:
# selecciono la tabla y entre corchetes agrego la nueva columna y le tengo que asignar un valor
df_exams["language score"] =70

0      70
1      70
2      70
3      70
4      70
       ..
995    70
996    70
997    70
998    70
999    70
Name: language score, Length: 1000, dtype: int64

In [16]:
# pero cada alumno deberia tener un diferente valor en sus notas
df_exams

gender race/ethnicity parental level of education         lunch  \
0    female        group B           bachelor's degree      standard   
1    female        group C                some college      standard   
2    female        group B             master's degree      standard   
3      male        group A          associate's degree  free/reduced   
4      male        group C                some college      standard   
..      ...            ...                         ...           ...   
995  female        group E             master's degree      standard   
996    male        group C                 high school  free/reduced   
997  female        group C                 high school  free/reduced   
998  female        group D                some college      standard   
999  female        group D                some college  free/reduced   

    test preparation course  math score  reading score  writing score  \
0                      none          72             72             74   
1                 completed          69             90             88   
2                      none          90             95             93   
3                      none          47             57             44   
4                      none          76             78             75   
..                      ...         ...            ...            ...   
995               completed          88             99             95   
996                    none          62             55             55   
997               completed          59             71             65   
998               completed          68             78             77   
999                    none          77             86             86   

     language score  
0                70  
1                70  
2                70  
3                70  
4                70  
..              ...  
995              70  
996              70  
997              70  
998              70  
999              70  

[1000 rows x 9 columns]

In [ ]:
# so, hay que ponerles una array, muchas arrays


# 1.2 Agregar una nueva columna con un array

In [ ]:
# ¿Qué es un array? Un array es una colección de elementos del mismo tipo de dato. 
# En cambio, una lista puede tener elementos de diferentes tipos de datos. 
# En la programación en Python, para crear un array, es necesario importar el módulo array porque un array no es 
# un tipo de datos fundamental.)

In [17]:
#import numpy . (biblioteca que da soporte para crear vectores y matrices grandes multidimensionales, 
# junto con funciones matemáticas de alto nivel)

In [18]:
import numpy as np

In [19]:
# voy a crear un array de 1000 elementos. a range
np.arange(0, 1000)

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [20]:
#uso la funcion len para varificar el largo
len(np.arange(0, 1000))

1000

In [21]:
# a ese rango le asigno un nombre a la variable 
language_score=(np.arange(0, 1000))

In [22]:
len(language_score)

1000

In [23]:
#adiciono una nueva columna a la tabla con un array
df_exams["language score"] = language_score

In [24]:
#para ver
df_exams

gender race/ethnicity parental level of education         lunch  \
0    female        group B           bachelor's degree      standard   
1    female        group C                some college      standard   
2    female        group B             master's degree      standard   
3      male        group A          associate's degree  free/reduced   
4      male        group C                some college      standard   
..      ...            ...                         ...           ...   
995  female        group E             master's degree      standard   
996    male        group C                 high school  free/reduced   
997  female        group C                 high school  free/reduced   
998  female        group D                some college      standard   
999  female        group D                some college  free/reduced   

    test preparation course  math score  reading score  writing score  \
0                      none          72             72             74   
1                 completed          69             90             88   
2                      none          90             95             93   
3                      none          47             57             44   
4                      none          76             78             75   
..                      ...         ...            ...            ...   
995               completed          88             99             95   
996                    none          62             55             55   
997               completed          59             71             65   
998               completed          68             78             77   
999                    none          77             86             86   

     language score  
0                 0  
1                 1  
2                 2  
3                 3  
4                 4  
..              ...  
995             995  
996             996  
997             997  
998             998  
999             999  

[1000 rows x 9 columns]

In [ ]:
ahora no tiene un solo valor, 70, sino una secuencia ue aumenta de a 1. Para solucionar eso vamos a aplicarle numeros r
random

In [40]:
#create random integer numbers entre 1 y 100 (1, 100) NO INCLUYE EL 100 y le agrego el tamaño de filas donde tiene que 
#llenar. Para eso se usa numpy. 1°minimo 2° maximo 3°tamaño a llenar
np.random.randint(1, 101, size=1000)


array([ 90,  31,  41,  74,  59,  78,   6,  17,  84,  89,   5,  90,  73,
        68,  99,  27,  50,  67,  10,  36,  41,  52,  50,  47,  26,  67,
        63,  50,  78,  67,  97,   1,  22,  34,  65,  47,  80, 100,  25,
        37,  46,  23,  43,  64,  20,  54,  33,  43,  60,  15,  85,  29,
        25,  24,  53, 100,  60,   1,  86,  98,  67,  62,  76,  78,  37,
        92,  30,  24,  84,  77,  25,  33,   5,  11,  62,  81,  10,  19,
        42,  54,  63,  38,  53,  77,  78,  29,  59,  83,  97,   5,  70,
        54,  21,  65,  24,  58,  60,  94,  79,  76,   7,   1,  73,  60,
        32,  97,   9,  61,  65,  70,  46,  23,  10,  10,  31,  44,  44,
        89,  72,  55,   5,  10,  63,  44,  10,  43,  75,  36,  81,  49,
        90,  67,  17,  78,  34,   5,  42,  13,  54,  51,   7,  42,  11,
        34,  51,  99,  39,  90,  84,  13,  38,  31,  24,  80,  94,  66,
        18,   4,  56,  14,  74,  76,  44,  12,  73,  11,  45,  31, 100,
        28,  25,  30,  71,  97,  35,  22,  51,  41,  62,  12,  5

In [35]:
int_language_score=np.random.randint(1, 100, size=1000)

In [36]:
min(int_language_score)

1

In [37]:
max(int_language_score)

99

In [43]:
# agregar una nueva columna a la tabla con un array .adding a new column to dataframe with an array
df_exams["language_score"] = int_language_score

In [42]:
df_exams

gender race/ethnicity parental level of education         lunch  \
0    female        group B           bachelor's degree      standard   
1    female        group C                some college      standard   
2    female        group B             master's degree      standard   
3      male        group A          associate's degree  free/reduced   
4      male        group C                some college      standard   
..      ...            ...                         ...           ...   
995  female        group E             master's degree      standard   
996    male        group C                 high school  free/reduced   
997  female        group C                 high school  free/reduced   
998  female        group D                some college      standard   
999  female        group D                some college  free/reduced   

    test preparation course  math score  reading score  writing score  \
0                      none          72             72             74   
1                 completed          69             90             88   
2                      none          90             95             93   
3                      none          47             57             44   
4                      none          76             78             75   
..                      ...         ...            ...            ...   
995               completed          88             99             95   
996                    none          62             55             55   
997               completed          59             71             65   
998               completed          68             78             77   
999                    none          77             86             86   

     language score  language_score  
0                 0              61  
1                 1              70  
2                 2              60  
3                 3              79  
4                 4              74  
..              ...             ...  
995             995              59  
996             996              25  
997             997              49  
998             998               3  
999             999              73  

[1000 rows x 10 columns]

In [44]:
#como crear numeros decimales random. se hace con numpy tb
np.random.uniform(1,100, size=1000)


array([39.07790855, 31.7986973 , 75.18856872, 24.84730795, 81.14910475,
       12.67508012, 40.58707684, 60.32189762, 12.72251812, 49.07548314,
       20.37042918, 48.13026795, 82.9378475 , 12.01674243, 82.79214547,
       59.070205  , 76.09036592, 89.94694854, 45.67346472, 50.20070522,
       37.50533192, 10.15639534,  8.56175809, 38.19489957, 86.29361155,
       65.60188619, 51.09913143,  5.13714025, 91.00707346, 69.43058112,
       61.34007215, 14.07338232,  7.04275825,  3.36965594, 37.85393768,
       30.2120909 , 26.99875184, 41.7115302 , 49.31196047, 13.89638274,
        2.22855571, 57.13241333, 75.71604772, 39.20242988, 93.4381996 ,
        8.88038489, 75.7826521 , 63.44472905, 96.0250696 , 98.92780201,
       70.21644096, 76.38382941, 62.52182616, 60.61659815, 35.01112732,
        2.17992644, 38.78724194, 60.08558004, 65.86738398, 18.96419735,
       34.11484054, 35.88193965, 71.98762645, 71.99002409, 72.12815071,
       87.7696437 , 88.14232192, 56.96207397, 18.10534206, 12.08

In [ ]:
np.random.uniform(1,100, size=1000)